version: '3'
services:
  web:
    build: ./solicitud
    ports:
      - "5000:5000"
  nginx:
    build: ./serversettings
    ports:
      - "80:80"
    links:
      - web
  db:
    build: ./database
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
